### ISSUE TITLE
sub folder error

### ISSUE THREAD

**Issue by fugitivers** [plrthink/react-native-zip-archive#10]
i have a zip file,   
1.Zip
       ---1.txt
       ---subFolder
            ---1.txt
couldn`t extract
is good if without subFolder

**Comment by plrthink** [comment]
Which platform you're using on? Android or iOS? I use this for both of this platform and it works well. Which path you are extracting to?

**Comment by fugitivers** [comment]
windows create zip file has error, linux is good

**Comment by plrthink** [comment]
@fugitivers You mean your development environment? Not tested on windows machine actually.

**Comment by plrthink** [comment]
I'm closing this issue since not active.

**Comment by KBepo** [comment]
Yeah i'm facing same problem as above. I have to manually generate those subfolders to be same as inside zip to make it work. Error gives that those subfolders do not exist and that's why it can't extract it.
