### ISSUE TITLE
File fails to unzip with FileNotFoundException on Android

### ISSUE THREAD

**Issue by MadisonBlake** [plrthink/react-native-zip-archive#14]
I am attempting to unzip an archive in Android with the following directory structure

A
-B
--File1.txt

When unzipping I get a FileNotFoundException: "open failed: ENOENT (No such file or directory)" when RNZipArchiveModule::extractFile is called for the first time.

I have found that when it is stepping through the entries in RNZipArchiveModule::unzipStream the following entries come in:
"A/B/" - directory doesn't get made 
"A/B/File1.txt" - throws exception (Because "A/B" isn't there)

Note that I am given this archive and do not have control on its creation (but I can extract it with other zip programs, so it _should_ be valid). When I attempt to create my own archive with same structure, everything works and I get the following entries:  
A/
A/B/
A/B/File1.txt

In terms of fixes, I have found that similar to https://github.com/plrthink/react-native-zip-archive/commit/96d62c727040dc32e5e9e3d11eb14f4ed4d5f835, also changing line 94 to mkdirs makes the first case work as the 2 directories can be created at once.

**Comment by plrthink** [comment]
Not very sure about what wrong with the first case, since I'm not familiar with native android development, so you can feel free to open a PR to correct this bug.

**Comment by jreziga** [comment]
Try to mkdir your subfolders of your zip... I know it's weird but it worked for me

**Comment by hujiudeyang** [comment]
it worked for me
@MadisonBlake 
Android => RNZipArchiveModule.java:73
`import java.io.BufferedInputStream;`
`..`
`private void unzipStream(String zipFilePath, String destDirectory, InputStream inputStream, long totalSize, Callback completionCallback) {
    try {
      File destDir = new File(destDirectory);
      if (!destDir.exists()) {
        destDir.mkdirs();
      }
      ZipInputStream zipIn = new ZipInputStream(inputStream);
      BufferedInputStream bin = new BufferedInputStream(zipIn); 

      ZipEntry entry;

      long extractedBytes = 0;

      updateProgress(0, 1, zipFilePath); // force 0%
      File fout=null;
      while((entry = zipIn.getNextEntry())!=null){  
        if(entry.isDirectory()) continue;  
        fout=new File(destDirectory, entry.getName());
        if(!fout.exists()){
          (new File(fout.getParent())).mkdirs();  
        }  
        FileOutputStream out=new FileOutputStream(fout);
        BufferedOutputStream Bout=new BufferedOutputStream(out);
        int b;  
        while((b=bin.read())!=-1){
          Bout.write(b); 
        }
        Bout.close();
        out.close();
        System.out.println(fout+"解压成功");      
      }  
      updateProgress(1, 1, zipFilePath); // force 100%
      bin.close();
      zipIn.close();
      completionCallback.invoke(null, null);
    } catch (Exception ex) {
      ex.printStackTrace();
      updateProgress(0, 1, zipFilePath); // force 0%
      completionCallback.invoke(makeErrorPayload(String.format("Couldn't extract %s", zipFilePath), ex));
    }
  }`

**Comment by plrthink** [comment]
@hujiudeyang There's some formatting issue, can you update the comment to fix it? Also, you can directly make a PR to improve that, which will be very grateful.

**Comment by Juanpe19** [comment]
Hi, I've been trying to find another solution because this isn't helping, I tried everything I have in mind and it just won't work.
I have the same exact problem, using "react-native": "0.43.3".
If anyone could update this issue it would be grate, thanks!

**Comment by plrthink** [comment]
@AmatsuZero
