### ISSUE TITLE
Is bluebird Really Needed Here

### ISSUE THREAD

**Issue by cancan101** [plrthink/react-native-zip-archive#2]
Does RN not ship with a better polyfill?

**Comment by plrthink** [comment]
@cancan101 I don't know actually. I simply use bluebird for convert callback to promise. Do you any better suggestion about this? Any ideas are appreciate.

**Comment by taion** [comment]
It seems excessive to re-polyfill promises entirely. What about using e.g. https://www.npmjs.com/package/es6-promisify?

**Comment by plrthink** [comment]
@cancan101 Ok, I would check this out. Thanks~

**Comment by plrthink** [comment]
Since this package is using es6-promisify now, I will close this issue.
