### ISSUE TITLE
[Breaking] 0.40 Add namespaced import React/* to headers

### ISSUE THREAD

**Issue by Ferb2012** [plrthink/react-native-zip-archive#23]
There is breaking change in react-native 0.40, please refer to https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by plrthink** [comment]
Wow, thank you.

I'm on vacation these days, so I would check that when I'm come back home.

**Comment by itinance** [comment]
https://github.com/plrthink/react-native-zip-archive/pull/24
