### ISSUE TITLE
New NPM release for RN >= 0.40

### ISSUE THREAD

**Issue by juhasuni** [plrthink/react-native-zip-archive#25]
Could you please create a new release for React Native 0.40? Current version (0.0.11) doesn't work with RN 0.40, but the master branch seems to already contain all the necessary changes.

**Comment by plrthink** [comment]
Yeah, sure. Actually, I'm planning to release a more stable version with a better doc and some fixtures. I would do this as soon as possible.

**Comment by plrthink** [comment]
Just submit a PR to fix this issue in the `next` branch.

In addition to fixtures, it also has some break changes.  So could you pls install it via github to test it?

**Comment by plrthink** [comment]
this is the PR https://github.com/plrthink/react-native-zip-archive/pull/29

**Comment by plrthink** [comment]
the new version has been published on npm so I would close this issue
