### ISSUE TITLE
how to add the libz library to target

### ISSUE THREAD

**Issue by WestleyArgentum** [plrthink/react-native-zip-archive#5]
Step 4 in the readme says we should `add the libz library to your target`, unfortunately I'm not quite sure what that means :)

Sorry to bug you, but I'd really appreciate help!

**Comment by WestleyArgentum** [comment]
Forgot to close -- for future reference it just means you have to add another library, and when you search for libz it will show up

**Comment by truonghoangphuc** [comment]
Hi Westley,

Sorry but I can't found libz ?

Thanks

**Comment by plrthink** [comment]
@truonghoangphuc You follow this gif

![out](https://cloud.githubusercontent.com/assets/2429369/18864517/579aab4a-84c9-11e6-8e54-e46bfa5c95df.gif)
