### ISSUE TITLE
Make it work with rnpm

### ISSUE THREAD

**Issue by Secretmapper** [plrthink/react-native-zip-archive#6]
rnpm is pretty much becoming the de facto react-native 'native' module linker, and it works with almost all modules I tried - react-native-zip-archive was the first one where it didn't.

It seems that linking `libz` manually fixed it. I'm not too familiar with native iOS development but maybe something to look at?

**Comment by plrthink** [comment]
Yeah, agree with you, but I'm also not familiar with native iOS development 😹 . I would try this later or you can fell free to open a PR.

**Comment by plrthink** [comment]
After searching around, I find this thread (https://github.com/rnpm/rnpm/issues/122) on rnpm's issue list.

So I think for now we should just waiting for the feature to be added in next version of rnpm and I would update the readme to warning rnpm users about linking libz after run `rnpm link`
